### PR TITLE
24h clock and clean up

### LINKED ISSUE #55: time
how to change from am/pm to 24H? i was looking at https://github.com/bypassiwastaken/skiovox-helper/blob/main/new-tab/time-display.js but i can't figure it out...

### PR DESCRIPTION
**Pull request by 3kh0**
Resolve #55

And also cleans up the code and make the formatting consistant

### CODE REVIEW

**Comment by bypassiwastaken** [comment]
please dont litter your pull request with semicolons next time. it makes it hard to tell what you actually changed

**Comment by bypassiwastaken** [comment]
also im not seeing where the "options" for 24h is?

**Comment by 3kh0** [comment]
image

**Comment by nathblade16** [comment]
> I like #66 more as it allows you to customize.

thanks :octocat:

**Pull request closed without merging**
