### PR TITLE
Battery Display Update

### PR DESCRIPTION
**Pull request by DanTCA1**
- Added a battery bar for percentage
- Restructured padding and text size for the center text
- Fixed an issue that caused the battery time to say infinity:NaN
- Changed the battery message to say full when battery is full
- Improved the time left message to be more adaptable

### CODE REVIEW

**Comment by blankuserrr** [comment]
Why are you using text elements instead of making an actual battery bar?

**Comment by DanTCA1** [comment]
These changes were just changes I made to my own extension, and tbh, I forgot that I could make a plain out bar. if you want, I could try implementing it

**Comment by blankuserrr** [comment]
> These changes were just changes I made to my own extension, and tbh, I forgot that I could make a plain out bar. if you want, I could try implementing it

it's alright, I already implemented a custom version into my own

**Comment by bypassiwastaken** [comment]
will try getting this one later as well. exam weeks coming up though so dont expect anything from this git for 10 days at least

**Comment by VillainsRule** [comment]
😏 69

**Pull request closed without merging**
