### PR TITLE
Alt+Shift+M

### PR DESCRIPTION
**Pull request by zek-c**
Add shortcut to open file manager, makes it easier and most people would want this. Gonna add more shortcuts that I like soon.

### CODE REVIEW

**Comment by bypassiwastaken** [comment]
good idea; will look at this later

**Comment by zek-c** [comment]
my bad i committedded to mainington let me undo those rq

**Comment by bypassiwastaken** [comment]
simply creating file-manager doesn't work for 2a users (see the onclick for the file manager icon in new-tab/main.html). also i do not think this is necessary

**Comment by zek-c** [comment]
ok i didnt know that 2a was so unbelievably mid that it doesnt work

**Comment by zek-c** [comment]
YOU ENDED UP ADDING THE SHIT ANYWAYS 😭

**Pull request closed without merging**
