### PR TITLE
Fullscreen Shortcut

### PR DESCRIPTION
**Pull request by felixs-alt**
Press alt+f to toggle fullscreen

### CODE REVIEW

**Comment by bypassiwastaken** [comment]
have you tested this? last time i checked using chrome.windows.update({state: "fullscreen"}) crashes skiovox, at least in 2a

**Comment by Honkychunkymonkey** [comment]
If I'm not mistaken, can't you just use the Chromebook built in fullscreen button?

**Comment by GoodMusic8596** [comment]
Yes I do believe windows state fullscreen crashes on 2a, but what about 2b and 2c :C

**Comment by Mazedotexe** [comment]
This is pretty easy to implement without a change in skiovox helper :) On 2b/2c (not sure if it works on 2a) you can use what's probably my second favorite extension, [Shortkeys](https://chromewebstore.google.com/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck), to create this hotkey. Download shortkeys and go to the extension options (`chrome-extension://logpjaacgmcbpdkdchjiaagddngobkck/options/options.html`) and import this:

```
  {
    "key": "alt+f",
    "label": "fullscreen",
    "action": "javascript",
    "code": "document.documentElement.requestFullscreen()",
    "blacklist": false,
    "activeInInputs": true
  }
```
Now all you have to do is click "save shortcuts" in the Shortcuts tab, and you're done! (Please note that in any open tabs you will have to reload the page before the hotkey works.)

**Comment by Mazedotexe** [comment]
@felixs-alt (answer) This is pretty easy to implement without a change in skiovox helper :) On 2b/2c (not sure if it works on 2a) you can use what's probably my second favorite extension, [Shortkeys](https://chromewebstore.google.com/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck), to create this hotkey. Download shortkeys and go to the extension options (`chrome-extension://logpjaacgmcbpdkdchjiaagddngobkck/options/options.html`) and import this:

```
  {
    "key": "alt+f",
    "label": "fullscreen",
    "action": "javascript",
    "code": "document.documentElement.requestFullscreen()",
    "blacklist": false,
    "activeInInputs": true
  }
```
Now all you have to do is click "save shortcuts" in the Shortcuts tab, and you're done! (Please note that in any open tabs you will have to reload the page before the hotkey works.)

**Comment by Mazedotexe** [comment]
@felixs-alt (answer) This is pretty easy to implement without a change in skiovox helper :) On 2b/2c (probably doesnt work on 2a) you can use what's probably my second favorite extension, [Shortkeys](https://chromewebstore.google.com/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck), to create this hotkey. Download shortkeys and go to the extension options (`chrome-extension://logpjaacgmcbpdkdchjiaagddngobkck/options/options.html`) and import this:

```
  {
    "key": "alt+f",
    "label": "fullscreen",
    "action": "javascript",
    "code": "document.documentElement.requestFullscreen()",
    "blacklist": false,
    "activeInInputs": true
  }
```
Now all you have to do is click "save shortcuts" in the Shortcuts tab, and you're done! (Please note that in any open tabs you will have to reload the page before the hotkey works.)

**Comment by zek-c** [comment]
if im correct, the fullscreen button has a name/ F key assigned to it. it might be maximizeScreen or F3 or something like that so you can somewhat get native functionality if you find the key name

**Comment by blankuserrr** [comment]
> if im correct, the fullscreen button has a name/ F key assigned to it. it might be maximizeScreen or F3 or something like that so you can somewhat get native functionality if you find the key name

I think it's F4

**Comment by bypassiwastaken** [comment]
crashing 2a is not acceptable so i doubt i will implement this in the way you want.

**Pull request closed without merging**
