### PR TITLE
Redo New tab CSS

### PR DESCRIPTION
**Pull request by fowntain**
I don't really know... I was bored and I'm practicing my CSS :)
Who am I? I'm the owner of [Skool](https://polarislearning.org). You can ask Echo and other people about me too.
**Also, you can ignore/delete replit config files. I forgot to remove those before making this.**
image

### CODE REVIEW

**Comment by fowntain** [comment]
> get rid of all gradients.

done, although i'm not sure how much better it looks now

**Comment by fowntain** [comment]
image

**Comment by 3kh0** [comment]
Lol it does not need to be so goofy with the gradients

**Comment by bypassiwastaken** [comment]
sorry but i dont think ill any different colors to this one. if you want to make your own you can just fork it and use that instead

**Comment by fowntain** [comment]
> sorry but i dont think ill any different colors to this one. if you want to make your own you can just fork it and use that instead

tf does that mean?? no offense but if you're gonna reject this can you at least make the new tab page at least a slight bit better?

**Pull request closed without merging**
