### PR TITLE
Hotkey + Backend Changes

### PR DESCRIPTION
**Pull request by DanTCA1**
- Fixed softlock where you could press ctrl + w and delete the final tab
- Hotkeys will now longer trigger when using something like chrome remote desktop (More services can be added down the line)

### CODE REVIEW

**Comment by bypassiwastaken** [comment]
interesting idea. might refactor later

**Comment by blankuserrr** [comment]
have you thought of trying to dynamically check if the page needs the shortcut you're using?

**Comment by DanTCA1** [comment]
> have you thought of trying to dynamically check if the page needs the shortcut you're using?

That's something outside my level of expertise, so I have no idea how to do that

**Comment by bypassiwastaken** [comment]
i dont think thats possible to do anyway.

**Comment by Epicminer256** [comment]
I have been daily driving https://codepen.io/ugs/pen/jxGyVN to prevent closing the entire window. It assigns "e.returnValue" on a "onbeforeunload" event listener, so I wonder if this can be triggered only if it is the last tab.

**Pull request closed without merging**
