### PR TITLE
newtab themes

### PR DESCRIPTION
**Pull request by zkayns**
switch between light and dark themes on newtab page

### CODE REVIEW

**Review by 3kh0 — CHANGES_REQUESTED** [review]
THe default is dark mode, that is all you need

**Comment by lukasexists** [comment]
> The default is dark mode, that is all you need

Some people have trouble reading dark pages, actually, and there is some research suggesting that dark mode reduces productivity. Having an option to switch it would be a good idea

**Comment by bypassiwastaken** [comment]
the idea is really good. however im not liking the implementation of this at all:
- you use multiple css files with the same content
- js is extremely bad
- doesnt follow my class style
i'll work on this myself (maybe with the ability for users to select their own color) and try to add it later

**Comment by bypassiwastaken** [comment]
i just added a feature based off your idea. definitely a useful feature to add but this pull request is now obsolete. thanks for the help

**Pull request closed without merging**
